### ISSUE TITLE
カテゴリカル変数化処理後の欠損値処理対象にカテゴリカルデータの特徴量が表示されない不具合

### ISSUE THREAD

**Issue by riku1021** [riku1021/SimpLyz#3]
カテゴリカル変数化処理後に欠損値処理のページに遷移すると、欠損値処理すべきカテゴリカルデータの特徴量が表示されない不具合が発生するため、それに対応お願いします。

**Comment by yukihito-jokyu** [comment]
load_dtype関数が原因。欠損値のnanを文字列として記録し、欠損値補完の対象から外れた。
