### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by yukihito-jokyu** [riku1021/SimpLyz#30]

**Comment by riku1021** [comment]
# データベース設計
-----------------------

## Userテーブル
| フィールド名 | データ型 | 説明 |
|--------|--------|--------|
| UserId | UUID | ユーザーの一意の識別子（主キー） |
| MeilAdress | VARCHAR(255) | ユーザーのメールアドレス |
| Password | VARCHAR(255) | ユーザーのパスワード |
| GeminiApiKey | VARCHAR(255) | ユーザーのGeminiApiKey |

## Csvテーブル
| フィールド名 | データ型 | 説明 |
|--------|--------|--------|
| CsvId | UUID | CSVファイルの一意の識別子（主キー） |
| CsvFile | Unknown | CSVファイル本体 |
| JsonFile | Unkown | 型情報が記載されたjsonファイル |
| UserId | UUID | ユーザーID（Userテーブルへの外部キー） |
| FileName | VARCHAR(255) | ファイル名 |
| DataSize | INT | データサイズ（バイト数） |
| DataColumns | INT | データのカラム数 |
| DataRows | INT | データの行数 |
| UploadDate | TIMESTAMP | アップロード日 |
| LastAccessedDate | TIMESTAMP | 最終更新日 |

**Comment by yukihito-jokyu** [comment]
frontendがどういうAPIを必要としているか記載して欲しい。

引数と返り値があれば分かりやすくてうれしいです。

**Comment by riku1021** [comment]
# Frontendが必要なAPI

| フィールド名 | 引数 | 戻り値 |
|--------|--------|--------|
| ユーザーを保存するAPI | UserId, MailAddress, Password | StatusMessage |
| Passwordを変更するAPI | UserId, NewPassword | StatusMessage |
| Passwordを確認するAPI | UserId, Password | StatusMessage |
| メールアドレスを変更するAPI | UserId, NewMailAddress | StatusMessage |
| ユーザーを認証するAPI | MailAddress, Password | UserId |
| ユーザーを削除するAPI | UserId | StatusMessage |
| GeminiApiKeyを保存するAPI | UserId, GeminiApiKey | StatusMessage |
| GeminiApiKeyを取得するAPI | UserId | GeminiApiKey |
| GeminiApiKeyを変更するAPI | UserId, NewGeminiApiKey | StatusMessage |
| ユーザーのCSVファイルを一覧で取得するAPI | UserId | CSVファイルの一覧 |
| CSVファイルを削除するAPI | UserId, CsvId | StatusMessage |
| 最終更新日を更新するAPI | UserId, CsvId, LastAccessedDate | StatusMessage |
| CSVファイルをアップロードするAPI | UserId, CsvFile | StatusMessage |

※ StatusMessage: "Success" or "Failed"

### CSVファイルの一覧の詳細
- **CsvId**: 各CSVファイルの一意の識別子（UUID）
- **CsvFileName**: CSVファイル名
- **DataSize**: データサイズ（バイト数）
- **DataColumns**: データのカラム数
- **DataRows**: データの行数
- **UploadDate**: アップロード日（タイムスタンプ）
- **LastAccessedDate**: 最終更新日（タイムスタンプ）

**Comment by riku1021** [comment]
仮で設計してみたから過不足あるときは適宜変更お願いします。

違和感のあるAPIがあったら教えてほしいです。

**Comment by yukihito-jokyu** [comment]
「CSVファイルをアップロードするAPI」のみcsvの情報(ファイル名やカラム数など)をデータベースに保存するためbackend経由になります。

**Comment by yukihito-jokyu** [comment]
# backendが必要なAPI

| フィールド名 | 引数 | 戻り値 |
|--------|--------|--------|
| csvファイル,jsonファイルをアップロードするAPI | CsvFile, JsonFile | StatusMessage |
| csvファイル,jsonファイルを取得するAPI | CsvId | CsvFile, JsonFile |

**Comment by riku1021** [comment]
@yukihito-jokyu 

ログイン関連だけ安全性とUUID発行のためにFirebaseのAuthenticationで管理しようと考えてるんだけどどう思う？
その場合、UserテーブルのMeilAdressとPasswordフィールドが不要になって、以下が必要なくなる。（パスワード・メールアドレスはAuthenticationで管理）

| API機能 | 引数 | 戻り値 |
|--------|--------|--------|
| ユーザーを保存するAPI | UserId, MailAddress, Password | StatusMessage |
| Passwordを変更するAPI | UserId, NewPassword | StatusMessage |
| Passwordを確認するAPI | UserId, Password | StatusMessage |
| メールアドレスを変更するAPI | UserId, NewMailAddress | StatusMessage |
| ユーザーを認証するAPI | MailAddress, Password | UserId |
| ユーザーを削除するAPI | UserId | StatusMessage |

### ※ユーザーを保存するAPIだけ変更

| API機能 | 引数 | 戻り値 |
|--------|--------|--------|
| ユーザーを保存するAPI | UserId | StatusMessage |

もしじゃない方が良いor戻れないとかだったら、元のままで、フロントエンドでUUID発行しようかなと思う。

**Comment by yukihito-jokyu** [comment]
ハッシュ化を実装したら安全性を担保できると思う。
実際に実装してみたかったので、FirebaseのAuthenticationではなく、データベースで管理したい。

**Comment by riku1021** [comment]
なるほど、ありがと、了解🫡

**Comment by yukihito-jokyu** [comment]
質問！
「Passwordを確認するAPI」はどのような場面で使われる？
「メールアドレスを変更するAPI」について、この処理は妥当か？

**Comment by riku1021** [comment]
回答！
・「Passwordを確認するAPI」は、GeminiApiKeyのを確認する時に入力してもらう。（デフォルトの表示は「・・・」）
・「この処理は妥当か？」が抽象的すぎるかも。詳しい疑問をお聞きしたい。

ちなみになんだけど、ログイン処理はどう考えてる？毎回、メアドとパスワード入力？

**Comment by yukihito-jokyu** [comment]
Passwordを確認するAPI->OK

「メールアドレスを変更するAPI」->既存のシステムやサービスに無いような機能だと思いました。僕のイメージとして一つのアカウントに一つのメールアドレスが基本だと思っていました。しかし、調べてみたらメールアドレスの変更があるようなので、実装しておきます。申し訳ません。

**Comment by yukihito-jokyu** [comment]
「GeminiApiKeyを変更するAPI」について「GeminiApiKeyを保存するAPI」と処理が同じなので実装しない方向になります。

**Comment by riku1021** [comment]
psql "postgresql://iriku@localhost/postgres"たたいて成功したときに\i admin/create.sqlたたいたらファイルがないってなった。原因わかる？？

具体的な現状
```
iriku@OK220164:~/myproject/SimpLyz$ psql "postgresql://iriku@localhost/postgres"
psql (14.13 (Homebrew))
Type "help" for help.

postgres=# \i admin/create.sql
admin/create.sql: No such file or directory
postgres=# 
```

**Comment by riku1021** [comment]
create database simplyzでデータベースができてないっぽい。。。原因わかる？？

iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$ psql "postgresql://admin@localhost/postgres"
psql (14.13 (Homebrew))
Type "help" for help.

postgres=# create database simplyz
postgres-# \q
iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$ psql -l
                         List of databases

|   Name    | Owner | Encoding | Collate | Ctype | Access privileges |
|-----------|-------|----------|---------|-------|-------------------|
| postgres  | iriku | UTF8     | C       | C     | |
| template0 | iriku | UTF8     | C       | C     | =c/iriku         +|
|           |       |          |         |       | iriku=CTc/iriku|
| template1 | iriku | UTF8     | C       | C     | =c/iriku         +|
|           |       |          |         |       | iriku=CTc/iriku|

(3 rows)

iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$

**Comment by riku1021** [comment]
> create database simplyzでデータベースができてないっぽい。。。原因わかる？？
> 
> iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$ psql "postgresql://admin@localhost/postgres" psql (14.13 (Homebrew)) Type "help" for help.
> 
> postgres=# create database simplyz postgres-# \q iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$ psql -l List of databases
> 
> Name	Owner	Encoding	Collate	Ctype	Access privileges
> postgres	iriku	UTF8	C	C	
> template0	iriku	UTF8	C	C	=c/iriku +
> iriku=CTc/iriku
> template1	iriku	UTF8	C	C	=c/iriku +
> iriku=CTc/iriku
> (3 rows)
> 
> iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$

create database simplyzではなくCREATE DATABASE simplyz;で作成された！

**Comment by riku1021** [comment]
Goの導入について、.zshrc ファイルってどこにある想定？

**Comment by yukihito-jokyu** [comment]
~ディレクトリにある想定
確認するコマンド
```bash
cd ~
ls -a
```

これで.zshrcがあるかどうか確認して欲しい。
もしなかったら、```ls```コマンド後の結果をスクリーンショット撮って直接送ってほしい

**Comment by yukihito-jokyu** [comment]
> create database simplyzでデータベースができてないっぽい。。。原因わかる？？
> 
> iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$ psql "postgresql://admin@localhost/postgres" psql (14.13 (Homebrew)) Type "help" for help.
> 
> postgres=# create database simplyz postgres-# \q iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$ psql -l List of databases
> 
> Name	Owner	Encoding	Collate	Ctype	Access privileges
> postgres	iriku	UTF8	C	C	
> template0	iriku	UTF8	C	C	=c/iriku +
> iriku=CTc/iriku
> template1	iriku	UTF8	C	C	=c/iriku +
> iriku=CTc/iriku
> (3 rows)
> 
> iriku@OK220164:~/myproject/SimpLyz/dev/database/sql$

おそらく```create database simplyz```の最後に```;```が無いのが原因かと

[参考サイト](https://www.javadrive.jp/postgresql/database/index2.html)

**Comment by riku1021** [comment]
なさそう。。。
![image](https://github.com/user-attachments/assets/f7099de2-5345-4691-b5f2-4a25d766944c)

**Comment by yukihito-jokyu** [comment]
zsh入ってない？

**Comment by riku1021** [comment]
入ってない。。

**Comment by riku1021** [comment]
> なさそう。。。 ![image](https://private-user-images.githubusercontent.com/139195765/384892255-f7099de2-5345-4691-b5f2-4a25d766944c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjI4MTcsIm5iZiI6MTczMTMyMjUxNywicGF0aCI6Ii8xMzkxOTU3NjUvMzg0ODkyMjU1LWY3MDk5ZGUyLTUzNDUtNDY5MS1iNWYyLTRhMjVkNzY2OTQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMDU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yjg4MzhhZWU3YjY4ZWNkZDE1NWFhMGUwNmZhZWMxNThlZTVjZWNhMGNlZTNlYTcyMjA3YjA3MzM1ZDdhOTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lcDcZpQpvO67ltIfyGhCSxqdzTf48qq8zODd3Y6mrZU)

これの表示ではなく？？

**Comment by yukihito-jokyu** [comment]
「GeminiApiKeyを取得するAPI」について

frontend側でGeminiのAPIを表示させるために必要と言っていたが、本当に表示させる必要性があるのか？

**Comment by riku1021** [comment]
@yukihito-jokyu 
すまん！確認漏れで申し訳ない。
「メールアドレスを変更するAPI」の実装忘れてるかも

追記：「メールアドレスを取得するAPI」作成した
