### ISSUE TITLE
描画グラフが日本語未対応

### ISSUE THREAD

**Issue by riku1021** [riku1021/SimpLyz#35]
添付画像のように「■」で表記されてしまう。

![image](https://github.com/user-attachments/assets/952087aa-c83e-4111-8151-952941276300)

**Comment by yukihito-jokyu** [comment]
対応します

**Comment by riku1021** [comment]
ランダムフォレストのグラフも対応よろしくです

**Comment by riku1021** [comment]
大変そうなので担当します。

**Comment by yukihito-jokyu** [comment]
感謝

**Comment by riku1021** [comment]
対応できました。
