### ISSUE TITLE
backend(python)にcsv_idを渡してほしい

### ISSUE THREAD

**Issue by yukihito-jokyu** [riku1021/SimpLyz#41]
csv操作を行う全てのpythonのAPIにcsv_idを渡してほしいです。csv操作を行う全てのAPiでgolang(postgresql)と通信を行い、csvファイルの呼び出しや更新を行う予定です。その際にcsv_idを用いて処理を行うので、frontendからbackendにcsv_idを渡してほしいです。

**Comment by riku1021** [comment]
了解です

**Comment by riku1021** [comment]
@yukihito-jokyu 
user_idも送るよね？？

**Comment by yukihito-jokyu** [comment]
csvのアップロード時以外はいらない。
