### ISSUE TITLE
Pythonにもパッケージ管理ツールを導入したい

### ISSUE THREAD

**Issue by yukihito-jokyu** [riku1021/SimpLyz#5]
現在、Pythonのパッケージ管理をrequirements.txtで実装しています。問題はありませんが、不便であるためnpmのようなパッケージ管理ツールを導入したいです。

[導入するパッケージ管理ツール](https://rye.astral.sh/guide/installation/)

**Comment by yukihito-jokyu** [comment]
@riku1021 

実装してよいかの確認欲しいです。

**Comment by riku1021** [comment]
いいと思う！

**Comment by yukihito-jokyu** [comment]
[ryeの基本的な使い方](https://qiita.com/hiseumn/items/5baa2eb44885dffc9bac#:~:text=%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%A7%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8BPython%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%81%BE%E3%81%99%E3%80%82%20terminal%20rye,use%20%3CPython%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%3E%20%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%A8%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B%20%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%A8%E3%81%9D%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%BE%E3%81%99%E3%80%82)
