### ISSUE TITLE
「users/check/user」APIについて

### ISSUE THREAD

**Issue by riku1021** [riku1021/SimpLyz#52]
users/check/userのAPIをたたいたときに以下のようなレスポンスだった。
![image](https://github.com/user-attachments/assets/2065e3c0-b6d8-4c66-ac8f-f59a6fbdc8d2)

caseが１，２，３の場合、StatusMessageはSuccessで管理するとgo-api_v3_0.pdfに記載していると思うので確認お願いします。

**Comment by yukihito-jokyu** [comment]
確認します

**Comment by yukihito-jokyu** [comment]
おそらく状況としては、新規登録時の処理ですよね。

```typescript
// UserForm.tsx

    if (valid) {
      try {
        let userId: string | undefined;
        if (isRegist) {
          userId = generateUUID();
          const statusMessage = await createUser(
            userId,
            formData.mail_address,
            formData.password
          );
          showSuccessAlert(statusMessage || "新規登録が成功しました", "");
```

UserForm.tsxを見たところ新規登録時にはcreateUser関数をたたいています。この関数は```users/create```APIなので、Falseが出るのは正常です。正しい処理順序は、createUserの前にUser.tsxファイルで定義したcheckUser関数を実行し、その結果に応じてユーザー側に処理方法を選択させます。

**Comment by riku1021** [comment]
言葉足らずで申し訳ない、「issue/32」ブランチにログインページ（UserLogin.tsx）及び新規登録ページ（UserSignup.tsx）の最新版がある

**Comment by yukihito-jokyu** [comment]
golang側のスペルミスでapiの通信ができない状態でした。一応issue/32へプルリク送っておきます。

**Comment by yukihito-jokyu** [comment]
1行だけだったのでプルリクをキャンセルします。

変更点はgolang/main.goの139行目の```uesrs```を```users```に変更してください。

**Comment by yukihito-jokyu** [comment]
変更してくれたので閉じます
