### ISSUE TITLE
チャット機能のデータベース設計について

### ISSUE THREAD

**Issue by yukihito-jokyu** [riku1021/SimpLyz#55]
<html>
<body>
<h1>scatter_roomテーブル</h1>

フィールド名 | 型 | 説明 | primary key | foreign key
-- | -- | -- | -- | --
csv_id | UUID | csvファイルに付与された一意のid |   | Y (csvs)
room_id | UUID | チャットルームに付与された一意のid | Y |  
vertical | VARCHAR(255) | verticalのカラム名 |   |  
horizontal | VARCHAR(255) | horizontalのカラム名 |   |  
target | VARCHAR(255) | targetのカラム名 |   |  
regression | BOOLEAN | 回帰をするかしないか |   |  

<h1>hist_roomテーブル</h1>

フィールド名 | 型 | 説明 | primary key | foreign key
-- | -- | -- | -- | --
csv_id | UUID | csvファイルに付与された一意のid |   | Y (csvs)
room_id | UUID | チャットルームに付与された一意のid | Y |  
vertical | VARCHAR(255) | verticalのカラム名 |   |  
target | VARCHAR(255) | targetのカラム名 |   |  

<h1>box_roomテーブル</h1>

フィールド名 | 型 | 説明 | primary key | foreign key
-- | -- | -- | -- | --
csv_id | UUID | csvファイルに付与された一意のid |   | Y (csvs)
room_id | UUID | チャットルームに付与された一意のid | Y |  
vertical | VARCHAR(255) | verticalのカラム名 |   |  
horizontal | VARCHAR(255) | horizontalのカラム名 |   |  

<h1>pie_roomテーブル</h1>

フィールド名 | 型 | 説明 | primary key | foreign key
-- | -- | -- | -- | --
csv_id | UUID | csvファイルに付与された一意のid |   | Y (csvs)
room_id | UUID | チャットルームに付与された一意のid | Y |  
vertical | VARCHAR(255) | verticalのカラム名 |   |  
horizontal | VARCHAR(255) | horizontalのカラム名 |   |  

<h1>chatsテーブル</h1>

フィールド名 | 型 | 説明 | primary key | foreign key
-- | -- | -- | -- | --
chat_id | UUID | csvファイルに付与された一意のid | Y |  
room_id | UUID | チャットルームに付与された一意のid |   |  
message | VARCHAR(255) | メッセージ |   |  
post_id | int(10) | チャットの順番を記載したもの |   |  
is_user | BOOLEAN | ユーザーのチャットかどうか |   |  

<h1>説明</h1>
<p>データ分析ページの左側のチャット欄を一つのroomと定義し、固有のroom_idを付与する。room_idの参照方法は○○_roomテーブルから各図の表示時のパラメータとcsv_idを基に行う。room_idを取得した後にchatsテーブルから対応するroom_idの全チャットを取得し、post_idフィールドを基に昇順並び替えを行い、is_userフィールドを基にfrontend側で表示方法を変えるようにしたい。</p>

</body>
</html>

**Comment by yukihito-jokyu** [comment]
@riku1021 
レビューお願いします。

**Comment by riku1021** [comment]
素晴らしいです。

**Comment by yukihito-jokyu** [comment]
一旦この構造で作成します

**Comment by yukihito-jokyu** [comment]
<html>
<body>
<h1>roomsテーブル</h1>

フィールド名 | 型 | 説明 | primary key | foreign key
-- | -- | -- | -- | --
room_id | UUID | チャットルームに付与された一意のid | Y |  
csv_id | UUID | csvファイルに付与された一意のid |   | Y (csvs)
visualization_type | VARCHAR(255) | ビジュアライゼーションの種類 |   |  
vertical | VARCHAR(255) | verticalのカラム名 |   |  
horizontal | VARCHAR(255) | horizontalのカラム名 |   |  
target | VARCHAR(255) | targetのカラム名 |   |  
regression | BOOLEAN | 回帰をするかしないか |   |  

<h1>chatsテーブル</h1>

フィールド名 | 型 | 説明 | primary key | foreign key
-- | -- | -- | -- | --
chat_id | UUID | csvファイルに付与された一意のid | Y |  
room_id | UUID | チャットルームに付与された一意のid |   | Y(rooms)
message | VARCHAR(255) | メッセージ |   |  
post_id | int(10) | チャットの順番を記載したもの |   |  
user_chat | BOOLEAN | ユーザーのチャットかどうか |   |  


</body>
</html>

**Comment by yukihito-jokyu** [comment]
○○_roomテーブルのフィールドに共通部分があったため、一つのroomsテーブルに集約しました。
また、is_userについて役割が「ユーザーのチャットかどうか」を判断するフィールドだと一目で分かるようにフィールド名を変更しました。
