### ISSUE TITLE
csvの復元機能をfrontendに実装してください

### ISSUE THREAD

**Issue by yukihito-jokyu** [riku1021/SimpLyz#57]

**Comment by riku1021** [comment]
CSVの復元機能の必要性がいまいちピンと来ていないです。

現状、CSVファイルを削除するとき、確認モーダルで確認してから削除する処理をするようにしている。よって、復元はこれと役割が重複するのではないか？
この機能限定で類似しているサービスで考えると、ファイルを管理するサービスであるGoogle Driveは復元機能を有していない。

もし、それでもファイルを復元する必要性があれば教えていただきたいです。

**Comment by riku1021** [comment]
@yukihito-jokyu
「CSVファイルの簡易情報取得API」の削除したCSVファイル版の作成をお願いします。

**Comment by yukihito-jokyu** [comment]
了解です！
