### ISSUE TITLE
batファイルについて

### ISSUE THREAD

**Issue by yukihito-jokyu** [riku1021/SimpLyz#7]
@riku1021 
pythonの仮想環境を立ち上げるコマンドとして「venv\Scripts\activate」が使われているが、ryeの初期化では、仮想環境のディレクトリ名が「.venv」となっているため、batファイルがうまく機能しません。今後ryeを使うなら「.venv」にしたいです。
また、frontend同様、パッケージの差分の更新を行うコマンドを追加したいです。

**Comment by riku1021** [comment]
batファイルの「venv\Scripts\activate」を「.venv\Scripts\activate」に変更するのみという認識で良いでしょうか？加えて、ryeに移行後はvenvディレクトリは削除しても良いでしょうか？

**Comment by yukihito-jokyu** [comment]
「.venv\Scripts\activate」に変更するで合ってます。また、rye移行前にvenvディレクトリの削除をお願いします。
変更の流れは以下の通りです。
batファイルの変更 -> 変更部分をpull -> venvディレクトリの削除 -> batファイルの起動
