### ISSUE TITLE
数的データを用いた計算でエラー発生

### ISSUE THREAD

**Issue by riku1021** [riku1021/SimpLyz#90]
「NumCompaniesWorked + NumCompaniesWorked」ができなかった。

確認方法は「docker-compose up --build」で起動して上記の式で特徴量エンジニアリング

**Comment by yukihito-jokyu** [comment]
解決したんですか？

**Comment by riku1021** [comment]
@yukihito-jokyu 
欠損値があるカラムを用いて特徴量エンジニアリングしようとしたことによるエラーだった。

解決方法が２通り思ってて、一つは、欠損値があるカラムを選択肢からなくす、もう一つが、式の中で欠損値がある行は欠損値で補完する。どっちがいいと思う？？

**Comment by riku1021** [comment]
どちらの場合も俺が対応しようと思う！

**Comment by yukihito-jokyu** [comment]
どちらの解決方法じゃないけど、欠損値があるカラムは、表示させておくが、灰色もしくは透明度を上げて選択できないようにさせるのが良いと思う。選択肢から消さない理由としては、そのカラムに対して特徴量を作成したいユーザーが困惑すると思うから。可能であれば、選択は出来ないけど、クリックしたときに補完が必要ですと呼びかけると更に困惑しないで済むと思う。

解決策の二つ目で言っていた欠損値がある行を欠損値で補完する(あまり理解してないけど...)のはユーザーが意図しないデータを作成する危険があるからやめた方がいいと思う。

**Comment by riku1021** [comment]
確かに！その手法にしようかと思う！

**Comment by riku1021** [comment]
@yukihito-jokyu
追加でもう一つ相談なんだけど、0除算の場合はどうしよう？
例えば、「id / id」にしたら、基本的に１になるはずだけど、「id」が０の場合、「0 / 0」で該当してエラーでたんだよね。。。
0 か None で補うのが良いかなと思うんだけどどう思う？？

**Comment by yukihito-jokyu** [comment]
個人的には割れないから None かな。けど、0で割れないこととNoneで補完されることをユーザーにも伝えなきゃいけないと思う。

**Comment by riku1021** [comment]
None -> 了解！
Noneで補完されることをユーザーにも伝達 -> ツールガイドページで説明するか、０除算のフラグをAPIからレスポンスで返して、モーダルで「０除算があったのでNoneで補完しました」的な表示をするかかな～

**Comment by yukihito-jokyu** [comment]
バックエンド側の特徴量作成APIで0除算があった場合に強制的にNoneで補完するフラグ(ifの条件分岐)を作っておく、初めは0除算があっても強制的にNoneで補完させない。モーダルで強制的にNoneで補完されることを記載し、OKを押したときに強制的にNoneに補完しながら特徴量を作成するようにするのはどう？
フラグ(if文)で見るのはフロントから送られてきたtrue,falseで初めは全てfalse。ユーザーがモーダルで強制的に保管されることを良しとする(OKボタンを押す)ことでtrueがバックエンドに送られ、if文で強制的にNoneで補完される処理はどうですか？

**Comment by riku1021** [comment]
つまり、決定を押すときに確認モーダルを表示するって認識であってる？
それで「OK」が押された場合、その時の特徴量エンジニアリングは0除算があっても強制的にNoneで補完ってことだよね。
その場合、「OK」が押されなかったときの挙動をどうするかだね

**Comment by yukihito-jokyu** [comment]
かなり処理がややこしいけど、0除算される場合のみ表示させる。

**Comment by yukihito-jokyu** [comment]
> バックエンド側の特徴量作成APIで0除算があった場合に強制的にNoneで補完するフラグ(ifの条件分岐)を作っておく、初めは0除算があっても強制的にNoneで補完させない。モーダルで強制的にNoneで補完されることを記載し、OKを押したときに強制的にNoneに補完しながら特徴量を作成するようにするのはどう？ フラグ(if文)で見るのはフロントから送られてきたtrue,falseで初めは全てfalse。ユーザーがモーダルで強制的に保管されることを良しとする(OKボタンを押す)ことでtrueがバックエンドに送られ、if文で強制的にNoneで補完される処理はどうですか？

ここで言っていたif文のelseに0除算があることをfrontendに伝える処理を記述するイメージ

**Comment by riku1021** [comment]
なるほどね！明日少し話そう！

**Comment by yukihito-jokyu** [comment]
これ対応しましょうか？
@riku1021 はドキュメントページのフォーマットを作成してほしいです。

**Comment by riku1021** [comment]
お願いします、了解！

**Comment by yukihito-jokyu** [comment]
もし作業途中でしたら、リモートブランチにpushしておいて欲しいです。

**Comment by riku1021** [comment]
現状メインが最新です。

**Comment by yukihito-jokyu** [comment]
了解です!
